version: '3.3'

services:

  frontend:
    image: daemondxx/balans-front:latest
    ports:
    - 80:80

  backend:
    image: daemondxx/balans-back:latest
    ports:
    - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./db_test/db:/data/db

